DROP TABLE IF EXISTS USUARIO;

CREATE TABLE IF NOT EXISTS USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDOS VARCHAR(255),
    EMAIL VARCHAR(255)
    -- Other columns you may need
);
